TemperatureMonitor/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dataDisplay/', include('dataDisplay.urls'))
    
]

dataDisplay/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2016-11-21 15:00:04
# @Author  : Alex Tang (1174779123@qq.com)
# @Link    : http://t1174779123.iteye.com
'''
	description:
'''

from django.conf.urls import url 
from . import views

app_name = 'dataDisplay'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<userid>[0-9]+)/addData/(?P<source>[a-z]+)/$', views.addData, name='addData'),
	url(r'^(?P<userid>[0-9]+)/input/$', views.input, name='input'),
	url(r'^(?P<userid>[0-9]+)/result/$', views.result, name='result'),
]

dataDisplay/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

'''
	数据表：
		1 User
		2 TempLog
'''

# Create your models here.

#用户类型
class User(models.Model):
	username = models.CharField(max_length = 30)
	password = models.CharField(max_length = 30)
	
#温度日志
class TempLog(models.Model):
	temperature = models.FloatField()
	recv_time = models.DateTimeField()
	recv_timestamp = models.IntegerField()
	user = models.ForeignKey(User, on_delete = models.CASCADE)

dataDisplay/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
import json, time

from .models import User, TempLog

# Create your views here.

# 数据显示主页
def index(request):
	return HttpResponse(u'这是dataDisplay的主页！')

#手动输入数据页面
def input(request, userid):
	user = get_object_or_404(User, pk=userid)
	return render(request, 'dataDisplay/input.html', {'user':user})

#添加数据页面
def addData(request, userid, source):
	user = get_object_or_404(User, pk=userid)
	temp = float(request.POST['temp'])
	recv_time = timezone.now()
	recv_timestamp = int(time.mktime(recv_time.timetuple()))
	templog = TempLog(temperature=temp, recv_time=recv_time, recv_timestamp=recv_timestamp, user=user)
	templog.save()
	if source == 'web':
		return HttpResponseRedirect(reverse('dataDisplay:result',args=(user.id,)))
	else:
		return HttpResponse(u'get wifi data')
#显示数据结果的页面
def result(request, userid):
	user = get_object_or_404(User, pk=userid)
	latest_templog_list = user.templog_set.order_by('-recv_time')[:100]
	context = {'latest_templog_list':latest_templog_list}
	return render(request, 'dataDisplay/result.html', context)

dataDisplay/templates/dataDisplay/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>温度监控</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
</head>
<body>
    
</body>
</html>

dataDisplay/templates/dataDisplay/input.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>输入数据</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
</head>
<body>
    <h1>请输入温度数据</h1>
    {% if error_message %}
    	<p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'dataDisplay:addData' user.id 'web' %}", method="post">
    	<label>输入温度</label>
    	<input type="text" name="temp"><br />
    	<input type="submit" value="提交">
    </form>
</body>
</html>

dataDisplay/templates/dataDisplay/result.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>数据结果</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
</head>
<body>
    {% for templog in latest_templog_list %}
    	<li>
    		<p>序号：{{ forloop.counter }}\t时间：{{ templog.recv_time }}\t温度：{{ templog.temperature }}</p>
    	</li>
    {% endfor %}
    <a href="{% url 'dataDisplay:input' user.id %}"></a>
</body>
</html>